on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: lts

      - name: lint
        run: deno lint

      - name: test
        run: deno test --unstable-kv
